import type { ArchitectureConfig } from '../types/simulation';

export interface PresetScenario {
  id: string;
  name: string;
  badge: string;
  badgeColor: string;
  description: string;
  learningOutcome: string;
  config: ArchitectureConfig;
}

export const PRESET_SCENARIOS: PresetScenario[] = [
  {
    id: 'scratch-canvas',
    name: 'Blank Canvas (Build from Scratch)',
    badge: 'Interactive Builder',
    badgeColor: 'bg-indigo-500/20 text-indigo-400 border-indigo-500/30',
    description: 'Start with a clean canvas. Use the (+) button to choose your tech stack, hosting provider, and database, then test real load.',
    learningOutcome: 'Assemble components step-by-step, choose real cloud specs, and discover how your architecture behaves under stress.',
    config: {
      name: 'Custom Architecture',
      description: 'Custom distributed system architecture',
      loadBalancer: {
        enabled: false,
        algorithm: 'round_robin',
        sslTermination: true,
        rateLimitRps: 0,
        activeInstances: 0,
      },
      servers: [],
      database: {
        id: 'db-1',
        name: 'postgres-primary',
        engine: 'postgres',
        provider: 'aws',
        instanceType: 'db.t4g.small',
        vCpu: 2,
        ramGb: 2,
        storageGb: 50,
        storageType: 'ebs_gp3',
        maxConnections: 100,
        hasConnectionPooler: false,
        poolerCapacity: 100,
        hasReadReplica: false,
        replicaCount: 0,
        status: 'healthy',
        activeConnections: 0,
        connectionPoolUtilization: 0,
        cpuUtilization: 5,
        ramUsedMb: 250,
        storageUsedGb: 8,
        bufferCacheHitRatio: 99,
        queriesPerSecond: 0,
        slowQueriesCount: 0,
        iopsSaturation: 5,
      },
      cache: {
        enabled: false,
        engine: 'redis',
        memoryGb: 1,
        hitRatio: 0,
        status: 'down',
        ramUsedMb: 0,
      },
      queue: {
        enabled: false,
        type: 'redis_bullmq',
        queueDepth: 0,
        processingRate: 0,
        deadLetterCount: 0,
        status: 'healthy',
      },
      traffic: {
        baseRps: 120,
        pattern: 'constant',
        spikeMultiplier: 3.5,
        spikeDurationSeconds: 15,
        distribution: {
          normalApiPercent: 70,
          heavyQueryPercent: 15,
          videoRenderPercent: 10,
          fileUploadPercent: 3,
          pdfReportPercent: 2,
        },
      },
    },
  },
  {
    id: 'video-monolith-crash',
    name: 'The Video Render Crash (Monolith Trap)',
    badge: 'OOM & Event Loop Freeze',
    badgeColor: 'bg-rose-500/20 text-rose-400 border-rose-500/30',
    description: 'A single Node.js server handling both regular API traffic AND heavy 1080p video rendering synchronously.',
    learningOutcome: 'Watch how CPU-heavy tasks block the single-threaded event loop and consume RAM, triggering Linux OOM Killer and 504 Gateway Timeouts.',
    config: {
      name: 'Single Node.js Monolith with Synchronous Video Processing',
      description: 'Single t4g.small instance handling web API + FFmpeg video rendering',
      loadBalancer: {
        enabled: false,
        algorithm: 'round_robin',
        sslTermination: true,
        rateLimitRps: 0,
        activeInstances: 1,
      },
      servers: [
        {
          id: 'server-1',
          name: 'web-monolith-01',
          role: 'monolith',
          provider: 'aws',
          instanceType: 't4g.small',
          vCpu: 2,
          ramGb: 2,
          storageGb: 20,
          storageType: 'ebs_gp3',
          techStack: 'nodejs',
          workersCount: 1,
          status: 'healthy',
          cpuUtilization: 12,
          ramUsedMb: 350,
          ramUtilization: 17,
          storageUsedGb: 8.5,
          storageUtilization: 42,
          diskIopsUsed: 120,
          diskIopsLimit: 3000,
          activeConnections: 15,
          eventLoopLagMs: 2.1,
          threadsBusy: 2,
          threadsTotal: 4,
          uptimeSeconds: 120,
          restartCountdown: 0,
          totalCrashes: 0,
          crashReason: null,
        },
      ],
      database: {
        id: 'db-1',
        name: 'postgres-primary',
        engine: 'postgres',
        provider: 'aws',
        instanceType: 'db.t4g.small',
        vCpu: 2,
        ramGb: 2,
        storageGb: 50,
        storageType: 'ebs_gp3',
        maxConnections: 100,
        hasConnectionPooler: false,
        poolerCapacity: 100,
        hasReadReplica: false,
        replicaCount: 0,
        status: 'healthy',
        activeConnections: 12,
        connectionPoolUtilization: 12,
        cpuUtilization: 15,
        ramUsedMb: 600,
        storageUsedGb: 12,
        bufferCacheHitRatio: 88,
        queriesPerSecond: 45,
        slowQueriesCount: 0,
        iopsSaturation: 10,
      },
      cache: {
        enabled: false,
        engine: 'redis',
        memoryGb: 1,
        hitRatio: 0,
        status: 'down',
        ramUsedMb: 0,
      },
      queue: {
        enabled: false,
        type: 'redis_bullmq',
        queueDepth: 0,
        processingRate: 0,
        deadLetterCount: 0,
        status: 'healthy',
      },
      traffic: {
        baseRps: 180,
        pattern: 'spike',
        spikeMultiplier: 3.5,
        spikeDurationSeconds: 15,
        distribution: {
          normalApiPercent: 65,
          heavyQueryPercent: 15,
          videoRenderPercent: 12,
          fileUploadPercent: 5,
          pdfReportPercent: 3,
        },
      },
    },
  },
  {
    id: 'black-friday-db-meltdown',
    name: 'Black Friday Spike (DB Pool Exhaustion)',
    badge: 'Database Saturated',
    badgeColor: 'bg-amber-500/20 text-amber-400 border-amber-500/30',
    description: 'Multiple web servers overwhelmed by flash crowd traffic, saturating PostgreSQL max connections without PgBouncer or Redis cache.',
    learningOutcome: 'Observe how horizontal scaling without database connection pooling causes "too many connections" errors and cascading timeouts.',
    config: {
      name: 'Scaled Web Tier with Saturated Database',
      description: '4 FastAPI instances exhausting PostgreSQL connection limit',
      loadBalancer: {
        enabled: true,
        algorithm: 'round_robin',
        sslTermination: true,
        rateLimitRps: 0,
        activeInstances: 4,
      },
      servers: [
        {
          id: 'server-1',
          name: 'api-worker-01',
          role: 'api_server',
          provider: 'digitalocean',
          instanceType: 'Basic Droplet',
          vCpu: 2,
          ramGb: 4,
          storageGb: 40,
          storageType: 'ssd',
          techStack: 'python',
          workersCount: 4,
          status: 'healthy',
          cpuUtilization: 25,
          ramUsedMb: 850,
          ramUtilization: 21,
          storageUsedGb: 10,
          storageUtilization: 25,
          diskIopsUsed: 150,
          diskIopsLimit: 3000,
          activeConnections: 45,
          eventLoopLagMs: 0,
          threadsBusy: 4,
          threadsTotal: 8,
          uptimeSeconds: 300,
          restartCountdown: 0,
          totalCrashes: 0,
          crashReason: null,
        },
        {
          id: 'server-2',
          name: 'api-worker-02',
          role: 'api_server',
          provider: 'digitalocean',
          instanceType: 'Basic Droplet',
          vCpu: 2,
          ramGb: 4,
          storageGb: 40,
          storageType: 'ssd',
          techStack: 'python',
          workersCount: 4,
          status: 'healthy',
          cpuUtilization: 25,
          ramUsedMb: 850,
          ramUtilization: 21,
          storageUsedGb: 10,
          storageUtilization: 25,
          diskIopsUsed: 150,
          diskIopsLimit: 3000,
          activeConnections: 45,
          eventLoopLagMs: 0,
          threadsBusy: 4,
          threadsTotal: 8,
          uptimeSeconds: 300,
          restartCountdown: 0,
          totalCrashes: 0,
          crashReason: null,
        },
        {
          id: 'server-3',
          name: 'api-worker-03',
          role: 'api_server',
          provider: 'digitalocean',
          instanceType: 'Basic Droplet',
          vCpu: 2,
          ramGb: 4,
          storageGb: 40,
          storageType: 'ssd',
          techStack: 'python',
          workersCount: 4,
          status: 'healthy',
          cpuUtilization: 25,
          ramUsedMb: 850,
          ramUtilization: 21,
          storageUsedGb: 10,
          storageUtilization: 25,
          diskIopsUsed: 150,
          diskIopsLimit: 3000,
          activeConnections: 45,
          eventLoopLagMs: 0,
          threadsBusy: 4,
          threadsTotal: 8,
          uptimeSeconds: 300,
          restartCountdown: 0,
          totalCrashes: 0,
          crashReason: null,
        },
        {
          id: 'server-4',
          name: 'api-worker-04',
          role: 'api_server',
          provider: 'digitalocean',
          instanceType: 'Basic Droplet',
          vCpu: 2,
          ramGb: 4,
          storageGb: 40,
          storageType: 'ssd',
          techStack: 'python',
          workersCount: 4,
          status: 'healthy',
          cpuUtilization: 25,
          ramUsedMb: 850,
          ramUtilization: 21,
          storageUsedGb: 10,
          storageUtilization: 25,
          diskIopsUsed: 150,
          diskIopsLimit: 3000,
          activeConnections: 45,
          eventLoopLagMs: 0,
          threadsBusy: 4,
          threadsTotal: 8,
          uptimeSeconds: 300,
          restartCountdown: 0,
          totalCrashes: 0,
          crashReason: null,
        },
      ],
      database: {
        id: 'db-1',
        name: 'postgres-standalone',
        engine: 'postgres',
        provider: 'digitalocean',
        instanceType: 'Managed Postgres 2vCPU',
        vCpu: 2,
        ramGb: 4,
        storageGb: 50,
        storageType: 'ssd',
        maxConnections: 100,
        hasConnectionPooler: false,
        poolerCapacity: 100,
        hasReadReplica: false,
        replicaCount: 0,
        status: 'healthy',
        activeConnections: 85,
        connectionPoolUtilization: 85,
        cpuUtilization: 78,
        ramUsedMb: 3200,
        storageUsedGb: 28,
        bufferCacheHitRatio: 65,
        queriesPerSecond: 1200,
        slowQueriesCount: 14,
        iopsSaturation: 65,
      },
      cache: {
        enabled: false,
        engine: 'redis',
        memoryGb: 1,
        hitRatio: 0,
        status: 'down',
        ramUsedMb: 0,
      },
      queue: {
        enabled: false,
        type: 'redis_bullmq',
        queueDepth: 0,
        processingRate: 0,
        deadLetterCount: 0,
        status: 'healthy',
      },
      traffic: {
        baseRps: 800,
        pattern: 'spike',
        spikeMultiplier: 4,
        spikeDurationSeconds: 20,
        distribution: {
          normalApiPercent: 40,
          heavyQueryPercent: 50,
          videoRenderPercent: 0,
          fileUploadPercent: 2,
          pdfReportPercent: 8,
        },
      },
    },
  },
  {
    id: 'resilient-production-architecture',
    name: 'Production Resilient System (Decoupled & Cached)',
    badge: 'High Performance & Stable',
    badgeColor: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30',
    description: 'Decoupled architecture: Golang API instances behind LB, Redis Cache (85% hit rate), PgBouncer, and dedicated background workers with BullMQ.',
    learningOutcome: 'Demonstrates rock-solid stability under 5,000+ RPS, sub-15ms latency, and zero server crashes even during video rendering.',
    config: {
      name: 'Resilient Scaled Architecture',
      description: 'Go API servers + Redis Cache + BullMQ Workers + PgBouncer Pool',
      loadBalancer: {
        enabled: true,
        algorithm: 'least_conn',
        sslTermination: true,
        rateLimitRps: 10000,
        activeInstances: 3,
      },
      servers: [
        {
          id: 'server-1',
          name: 'api-gateway-01',
          role: 'api_server',
          provider: 'aws',
          instanceType: 'c6i.large',
          vCpu: 2,
          ramGb: 4,
          storageGb: 30,
          storageType: 'nvme',
          techStack: 'go',
          workersCount: 2,
          status: 'healthy',
          cpuUtilization: 18,
          ramUsedMb: 240,
          ramUtilization: 6,
          storageUsedGb: 5,
          storageUtilization: 16,
          diskIopsUsed: 80,
          diskIopsLimit: 10000,
          activeConnections: 120,
          eventLoopLagMs: 0,
          threadsBusy: 12,
          threadsTotal: 100,
          uptimeSeconds: 7200,
          restartCountdown: 0,
          totalCrashes: 0,
          crashReason: null,
        },
        {
          id: 'server-2',
          name: 'api-gateway-02',
          role: 'api_server',
          provider: 'aws',
          instanceType: 'c6i.large',
          vCpu: 2,
          ramGb: 4,
          storageGb: 30,
          storageType: 'nvme',
          techStack: 'go',
          workersCount: 2,
          status: 'healthy',
          cpuUtilization: 18,
          ramUsedMb: 240,
          ramUtilization: 6,
          storageUsedGb: 5,
          storageUtilization: 16,
          diskIopsUsed: 80,
          diskIopsLimit: 10000,
          activeConnections: 120,
          eventLoopLagMs: 0,
          threadsBusy: 12,
          threadsTotal: 100,
          uptimeSeconds: 7200,
          restartCountdown: 0,
          totalCrashes: 0,
          crashReason: null,
        },
        {
          id: 'server-3',
          name: 'api-gateway-03',
          role: 'api_server',
          provider: 'aws',
          instanceType: 'c6i.large',
          vCpu: 2,
          ramGb: 4,
          storageGb: 30,
          storageType: 'nvme',
          techStack: 'go',
          workersCount: 2,
          status: 'healthy',
          cpuUtilization: 18,
          ramUsedMb: 240,
          ramUtilization: 6,
          storageUsedGb: 5,
          storageUtilization: 16,
          diskIopsUsed: 80,
          diskIopsLimit: 10000,
          activeConnections: 120,
          eventLoopLagMs: 0,
          threadsBusy: 12,
          threadsTotal: 100,
          uptimeSeconds: 7200,
          restartCountdown: 0,
          totalCrashes: 0,
          crashReason: null,
        },
        {
          id: 'worker-1',
          name: 'media-worker-01',
          role: 'worker',
          provider: 'aws',
          instanceType: 'c6i.xlarge',
          vCpu: 4,
          ramGb: 8,
          storageGb: 100,
          storageType: 'nvme',
          techStack: 'rust',
          workersCount: 4,
          status: 'healthy',
          cpuUtilization: 45,
          ramUsedMb: 2200,
          ramUtilization: 27,
          storageUsedGb: 25,
          storageUtilization: 25,
          diskIopsUsed: 650,
          diskIopsLimit: 12000,
          activeConnections: 8,
          eventLoopLagMs: 0,
          threadsBusy: 4,
          threadsTotal: 16,
          uptimeSeconds: 7200,
          restartCountdown: 0,
          totalCrashes: 0,
          crashReason: null,
        },
      ],
      database: {
        id: 'db-1',
        name: 'postgres-cluster',
        engine: 'postgres',
        provider: 'aws',
        instanceType: 'db.r6g.large',
        vCpu: 2,
        ramGb: 16,
        storageGb: 100,
        storageType: 'nvme',
        maxConnections: 200,
        hasConnectionPooler: true,
        poolerCapacity: 1000,
        hasReadReplica: true,
        replicaCount: 2,
        status: 'healthy',
        activeConnections: 35,
        connectionPoolUtilization: 17,
        cpuUtilization: 22,
        ramUsedMb: 4500,
        storageUsedGb: 32,
        bufferCacheHitRatio: 96,
        queriesPerSecond: 850,
        slowQueriesCount: 0,
        iopsSaturation: 18,
      },
      cache: {
        enabled: true,
        engine: 'redis',
        memoryGb: 4,
        hitRatio: 86,
        status: 'healthy',
        ramUsedMb: 1200,
      },
      queue: {
        enabled: true,
        type: 'redis_bullmq',
        queueDepth: 4,
        processingRate: 15,
        deadLetterCount: 0,
        status: 'healthy',
      },
      traffic: {
        baseRps: 2400,
        pattern: 'sinusoidal',
        spikeMultiplier: 2.2,
        spikeDurationSeconds: 15,
        distribution: {
          normalApiPercent: 70,
          heavyQueryPercent: 15,
          videoRenderPercent: 8,
          fileUploadPercent: 4,
          pdfReportPercent: 3,
        },
      },
    },
  },
  {
    id: 'storage-leak-disaster',
    name: 'Disk Storage Full Disaster',
    badge: 'Storage 100% Saturated',
    badgeColor: 'bg-purple-500/20 text-purple-400 border-purple-500/30',
    description: 'A small 10GB cloud instance where uncleaned temporary video transcode chunks and upload buffers fill up the disk completely.',
    learningOutcome: 'See how 100% disk usage causes database WAL failure, prevents process memory swap, and turns the file system read-only.',
    config: {
      name: 'Low Disk Volume with Uncleaned Temporary Files',
      description: '10GB droplet running video rendering without S3 or temp directory cleanup',
      loadBalancer: {
        enabled: false,
        algorithm: 'round_robin',
        sslTermination: true,
        rateLimitRps: 0,
        activeInstances: 1,
      },
      servers: [
        {
          id: 'server-1',
          name: 'render-node-01',
          role: 'monolith',
          provider: 'digitalocean',
          instanceType: 'Standard 10GB',
          vCpu: 2,
          ramGb: 4,
          storageGb: 10,
          storageType: 'ssd',
          techStack: 'python',
          workersCount: 2,
          status: 'healthy',
          cpuUtilization: 30,
          ramUsedMb: 1200,
          ramUtilization: 30,
          storageUsedGb: 8.8,
          storageUtilization: 88,
          diskIopsUsed: 400,
          diskIopsLimit: 3000,
          activeConnections: 25,
          eventLoopLagMs: 0,
          threadsBusy: 2,
          threadsTotal: 4,
          uptimeSeconds: 500,
          restartCountdown: 0,
          totalCrashes: 0,
          crashReason: null,
        },
      ],
      database: {
        id: 'db-1',
        name: 'sqlite-local-db',
        engine: 'postgres',
        provider: 'digitalocean',
        instanceType: 'Local Shared DB',
        vCpu: 2,
        ramGb: 2,
        storageGb: 10,
        storageType: 'ssd',
        maxConnections: 100,
        hasConnectionPooler: false,
        poolerCapacity: 100,
        hasReadReplica: false,
        replicaCount: 0,
        status: 'healthy',
        activeConnections: 18,
        connectionPoolUtilization: 18,
        cpuUtilization: 25,
        ramUsedMb: 600,
        storageUsedGb: 8.8,
        bufferCacheHitRatio: 90,
        queriesPerSecond: 80,
        slowQueriesCount: 0,
        iopsSaturation: 20,
      },
      cache: {
        enabled: false,
        engine: 'redis',
        memoryGb: 1,
        hitRatio: 0,
        status: 'down',
        ramUsedMb: 0,
      },
      queue: {
        enabled: false,
        type: 'redis_bullmq',
        queueDepth: 0,
        processingRate: 0,
        deadLetterCount: 0,
        status: 'healthy',
      },
      traffic: {
        baseRps: 120,
        pattern: 'constant',
        spikeMultiplier: 1.5,
        spikeDurationSeconds: 10,
        distribution: {
          normalApiPercent: 40,
          heavyQueryPercent: 10,
          videoRenderPercent: 30,
          fileUploadPercent: 15,
          pdfReportPercent: 5,
        },
      },
    },
  },
];
